# Generated by Django 2.1.1 on 2018-09-18 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=20)),
                ('nota', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('num_valoraciones', models.IntegerField(default=0)),
                ('aceptada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CosasPorVer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_a_visitar', models.DateField(blank=True, null=True)),
                ('visto', models.BooleanField()),
                ('fecha_visitado', models.DateField(blank=True, null=True)),
                ('orden', models.IntegerField(default=100)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Ciudad')),
            ],
            options={
                'ordering': ['visto', 'fecha_a_visitar'],
            },
        ),
        migrations.CreateModel(
            name='ElementoPresupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('usuario_paga', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('pagar_antes', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('Comida', 'Comida'), ('Monumento-Museo', 'Monumento-Museo'), ('Otro', 'Otro'), ('Transporte Publico', 'Transporte Publico'), ('Transporte', 'Transporte'), ('Alojamiento', 'Alojamiento')], default='Otro', max_length=20)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='EntradaForo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=280)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Ciudad')),
            ],
            options={
                'ordering': ['-fecha_realizacion'],
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('num_valoraciones', models.IntegerField(default=0)),
                ('monumento', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Valoracion',
            fields=[
                ('parametro', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PagoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('Por pagar', 'Por pagar'), ('Pagado', 'Pagado'), ('Usuario compra', 'Usuario compra')], default='Por pagar', max_length=20)),
                ('fecha_modificacion', models.DateField(auto_now_add=True)),
                ('idElementoPresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.ElementoPresupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('nombre_pais', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('continente', models.CharField(choices=[('Europa', 'Europa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('Africa', 'Africa'), ('America', 'America')], default='Europa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PuntuacionFoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Foto')),
                ('nombre_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Item_Valoracion')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(max_length=280)),
                ('lo_mejor', models.CharField(max_length=140)),
                ('lo_peor', models.CharField(max_length=140)),
                ('nombre_usuario', models.CharField(max_length=150)),
                ('media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Ciudad')),
            ],
            options={
                'ordering': ['-fecha_visita'],
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('coste_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_personas', models.IntegerField(blank=True, null=True)),
                ('planificacion', models.BooleanField()),
                ('usuario_creador', models.CharField(default='', max_length=150)),
                ('ciudades', models.ManyToManyField(to='web_viajes.Ciudad')),
                ('usuarios', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='valor',
            name='valoracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Valoracion'),
        ),
        migrations.AddField(
            model_name='foto',
            name='idViaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Viaje'),
        ),
        migrations.AddField(
            model_name='foto',
            name='nombre_ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Ciudad'),
        ),
        migrations.AddField(
            model_name='foto',
            name='nombre_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementopresupuesto',
            name='idViaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Viaje'),
        ),
        migrations.AddField(
            model_name='cosasporver',
            name='idViaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Viaje'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombre_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_viajes.Pais'),
        ),
        migrations.AlterUniqueTogether(
            name='valor',
            unique_together={('valoracion', 'parametro')},
        ),
        migrations.AlterUniqueTogether(
            name='pagousuario',
            unique_together={('idElementoPresupuesto', 'nombre_usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='elementopresupuesto',
            unique_together={('idViaje', 'concepto')},
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('nombre_ciudad', 'nombre_pais')},
        ),
    ]
