# Generated by Django 2.1.1 on 2018-09-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pais',
            name='continente',
        ),
        migrations.AlterField(
            model_name='elementopresupuesto',
            name='tipo',
            field=models.CharField(choices=[('Transporte', 'Transporte'), ('Monumento-Museo', 'Monumento-Museo'), ('Alojamiento', 'Alojamiento'), ('Otro', 'Otro'), ('Comida', 'Comida'), ('Transporte Publico', 'Transporte Publico')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagousuario',
            name='estado',
            field=models.CharField(choices=[('Por pagar', 'Por pagar'), ('Usuario compra', 'Usuario compra'), ('Pagado', 'Pagado')], default='Por pagar', max_length=20),
        ),
    ]
