# Generated by Django 2.0.6 on 2018-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopresupuesto',
            name='tipo',
            field=models.CharField(choices=[('Transporte Publico', 'Transporte Publico'), ('Alojamiento', 'Alojamiento'), ('Monumento-Museo', 'Monumento-Museo'), ('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Otro', 'Otro')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagousuario',
            name='estado',
            field=models.CharField(choices=[('Usuario compra', 'Usuario compra'), ('Por pagar', 'Por pagar'), ('Pagado', 'Pagado')], default='Por pagar', max_length=20),
        ),
    ]
