# Generated by Django 2.0.6 on 2018-09-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_viajes', '0002_auto_20180925_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopresupuesto',
            name='tipo',
            field=models.CharField(choices=[('Transporte Publico', 'Transporte Publico'), ('Alojamiento', 'Alojamiento'), ('Transporte', 'Transporte'), ('Monumento-Museo', 'Monumento-Museo'), ('Otro', 'Otro'), ('Comida', 'Comida')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagousuario',
            name='estado',
            field=models.CharField(choices=[('Por pagar', 'Por pagar'), ('Pagado', 'Pagado'), ('Usuario compra', 'Usuario compra')], default='Por pagar', max_length=20),
        ),
    ]
