# Generated by Django 2.0.6 on 2018-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_viajes', '0003_auto_20180925_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopresupuesto',
            name='tipo',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Transporte Publico', 'Transporte Publico'), ('Comida', 'Comida'), ('Transporte', 'Transporte'), ('Monumento-Museo', 'Monumento-Museo'), ('Alojamiento', 'Alojamiento')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagousuario',
            name='estado',
            field=models.CharField(choices=[('Por pagar', 'Por pagar'), ('Usuario compra', 'Usuario compra'), ('Pagado', 'Pagado')], default='Por pagar', max_length=20),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='fecha_visita',
            field=models.DateTimeField(),
        ),
    ]
