# Generated by Django 2.0.6 on 2018-12-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_viajes', '0004_auto_20181012_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopresupuesto',
            name='tipo',
            field=models.CharField(choices=[('Transporte Publico', 'Transporte Publico'), ('Monumento-Museo', 'Monumento-Museo'), ('Transporte', 'Transporte'), ('Comida', 'Comida'), ('Otro', 'Otro'), ('Alojamiento', 'Alojamiento')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagousuario',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Usuario compra', 'Usuario compra'), ('Por pagar', 'Por pagar')], default='Por pagar', max_length=20),
        ),
    ]
