# Generated by Django 2.1.4 on 2018-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_viajes', '0005_auto_20181201_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementopresupuesto',
            name='tipo',
            field=models.CharField(choices=[('Transporte', 'Transporte'), ('Comida', 'Comida'), ('Alojamiento', 'Alojamiento'), ('Otro', 'Otro'), ('Transporte Publico', 'Transporte Publico'), ('Monumento-Museo', 'Monumento-Museo')], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='pagousuario',
            name='estado',
            field=models.CharField(choices=[('Pagado', 'Pagado'), ('Por pagar', 'Por pagar'), ('Usuario compra', 'Usuario compra')], default='Por pagar', max_length=20),
        ),
    ]
